---
- name: UPDATE THE SNMP RO/RW STRINGS
  hosts: cisco
  gather_facts: no

  tasks:

    - name: ENSURE THAT THE DESIRED SNMP STRINGS ARE PRESENT
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW
          - snmp-server community ansible-test RW

